#ifndef HNRP_KEYWORDS_LIST_INCLUDED
#define HNRP_KEYWORDS_LIST_INCLUDED

// Keywords that need define/undefine in substrates/packages.

// Attributes
#undef ATTRIBUTES_NEED_NORMAL
#undef ATTRIBUTES_NEED_TANGENT
#undef ATTRIBUTES_NEED_UV0
#undef ATTRIBUTES_NEED_UV1
#undef ATTRIBUTES_NEED_UV2
#undef ATTRIBUTES_NEED_UV3
#undef ATTRIBUTES_NEED_COLOR

// Lit
#undef USE_POSITION_WS_VARYING
#undef USE_NORMAL_WS_VARYING
#undef USE_TANGENT_WS_VARYING
#undef USE_UV0_VARYING
#undef USE_UV1_VARYING
#undef USE_UV2_VARYING
#undef USE_UV3_VARYING
#undef USE_COLOR_VARYING
#undef USE_STATIC_LIGHTMAP_UV_VARYING
#undef USE_DYNAMIC_LIGHTMAP_UV_VARYING
#undef USE_VERTEX_SH_VARYING

#endif