using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace HN.HNRP
{
    /// <summary>
    /// Central registry for <see cref="Pass"/> types discovered via the <see cref="PassAttribute"/>.
    /// Provides fast name-based lookup and enumeration of all registered render passes.
    /// </summary>
    /// <remarks>
    /// In Editor, <see cref="RegisterAll"/> scans loaded assemblies for types decorated with
    /// <c>[Pass]</c>. In Player builds, code generation is preferred to avoid reflection overhead
    /// — see <c>PassRegistryGenerated.cs</c> which is generated by <c>PassRegistryGenerator</c>
    /// during the build process.
    ///
    /// <para>
    /// Registration order:
    /// <list type="number">
    /// <item><see cref="RegisterGenerated"/> — hardcoded table (Player builds)</item>
    /// <item>Reflection scan — <c>#if UNITY_EDITOR</c> only (catches newly-added passes)</item>
    /// </list>
    /// </para>
    /// </remarks>
    public static partial class PassRegistry
    {
        /// <summary>
        /// Maps display names to concrete <see cref="Pass"/> subclasses.
        /// Key is the <see cref="PassAttribute.DisplayName"/>,
        /// value is the <see cref="Type"/> decorated with that attribute.
        /// </summary>
        private static readonly Dictionary<string, Type> RegisteredPasses = new();

        /// <summary>
        /// Registers a <see cref="Pass"/> type under the given display name.
        /// Duplicate names silently overwrite previous entries.
        /// </summary>
        /// <param name="name">The display name to register under.</param>
        /// <param name="type">
        /// The concrete <see cref="Type"/> (must be a subclass of <see cref="Pass"/>).
        /// </param>
        public static void Register(string name, Type type)
        {
            if (name == null)
            {
                throw new ArgumentNullException(nameof(name));
            }

            if (type == null)
            {
                throw new ArgumentNullException(nameof(type));
            }

            RegisteredPasses[name] = type;
        }

        /// <summary>
        /// Partial method implemented by the auto-generated
        /// <c>PassRegistryGenerated.cs</c> file. Contains hardcoded
        /// <c>Register("Name", typeof(ConcretePass))</c> calls for zero-reflection
        /// Player builds.
        /// </summary>
        /// <remarks>
        /// In Editor, the generated file may be empty (all registrations via reflection).
        /// In Player builds, this method provides all registrations.
        /// </remarks>
        static partial void RegisterGenerated();

        /// <summary>
        /// Scans all loaded assemblies for types decorated with <see cref="PassAttribute"/>
        /// and adds them to the internal registry.
        /// </summary>
        /// <remarks>
        /// Only non-abstract classes that inherit from <see cref="Pass"/> and are decorated with
        /// <c>[Pass("Name")]</c> are registered. Duplicate names silently overwrite previous entries.
        ///
        /// <para>
        /// Registration order:
        /// <list type="number">
        /// <item>Calls <see cref="RegisterGenerated"/> — hardcoded table from code generation</item>
        /// <item>Editor-only reflection scan — discovers passes added since last generation</item>
        /// </list>
        /// </para>
        /// </remarks>
        public static void RegisterAll()
        {
            RegisteredPasses.Clear();

            // Step 1: hardcoded registrations from generated code (zero-reflection in Player)
            RegisterGenerated();

#if UNITY_EDITOR
            // Step 2: reflection scan — covers passes added since last code generation
            foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type[] types;
                try
                {
                    types = assembly.GetTypes();
                }
                catch (ReflectionTypeLoadException)
                {
                    // Skip assemblies that can't be loaded (e.g. broken references)
                    continue;
                }

                foreach (Type type in types)
                {
                    if (!type.IsAbstract &&
                        type.IsSubclassOf(typeof(Pass)) &&
                        type.GetCustomAttribute<PassAttribute>() is { } attr)
                    {
                        RegisteredPasses[attr.DisplayName] = type;
                    }
                }
            }
#endif
        }

        /// <summary>
        /// Looks up a registered <see cref="Pass"/> type by its display name.
        /// </summary>
        /// <param name="name">The <see cref="PassAttribute.DisplayName"/> to search for.</param>
        /// <returns>
        /// The <see cref="Type"/> if found; otherwise, <c>null</c>.
        /// </returns>
        public static Type GetPassType(string name)
        {
            if (name == null)
            {
                return null;
            }

            RegisteredPasses.TryGetValue(name, out Type type);
            return type;
        }

        /// <summary>
        /// Returns all registered pass display names.
        /// </summary>
        /// <returns>
        /// An enumerable of all display names currently in the registry.
        /// </returns>
        public static IEnumerable<string> GetAllPassNames()
        {
            return RegisteredPasses.Keys;
        }

        /// <summary>
        /// Creates a new <see cref="Pass"/> instance by display name.
        /// Looks up the registered <see cref="Type"/> and instantiates it
        /// via <c>Activator.CreateInstance</c> with the given instance name.
        /// </summary>
        /// <param name="displayName">
        /// The <see cref="PassAttribute.DisplayName"/> of the pass to create.
        /// </param>
        /// <param name="instanceName">
        /// The instance name for the new pass, passed to its string constructor.
        /// </param>
        /// <returns>
        /// The newly created <see cref="Pass"/> instance, or <c>null</c> if the
        /// display name is not registered or instantiation fails.
        /// </returns>
        /// <remarks>
        /// <para>
        /// The target <see cref="Pass"/> subclass must have a public constructor
        /// that accepts a single <see cref="string"/> argument (the instance name).
        /// If no such constructor exists, <c>null</c> is returned.
        /// </para>
        /// </remarks>
        public static Pass CreatePass(string displayName, string instanceName)
        {
            if (displayName == null || instanceName == null)
            {
                return null;
            }

            if (!RegisteredPasses.TryGetValue(displayName, out Type type))
            {
                return null;
            }

            try
            {
                return (Pass)Activator.CreateInstance(type, instanceName);
            }
            catch
            {
                return null;
            }
        }
    }
}
